name: Build Linux Executable

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        runtime:
          - linux-x64
          - linux-armv7l
          - linux-arm64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (Ubuntu)
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies (Ubuntu)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable (Ubuntu)
        run: pyinstaller --noconfirm --windowed main.py

      - name: Upload artifact (Ubuntu)
        uses: actions/upload-artifact@v4
        with:
          name: PassManaging-ubuntu-${{ matrix.runtime }}-v_${{ github.sha }}
          path: dist/

      - name: Build for Fedora in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app fedora:latest bash -c "
            dnf install -y python3-pip python3-devel gcc make &&
            python3 -m pip install --upgrade pip &&
            pip3 install -r requirements.txt &&
            pip3 install pyinstaller &&
            pyinstaller --noconfirm --windowed main.py
          "

      - name: Upload artifact (Fedora)
        uses: actions/upload-artifact@v4
        with:
          name: PassManaging-fedora-${{ matrix.runtime }}-v_${{ github.sha }}
          path: dist/