name: Build Linux Executable

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-build:
    strategy:
      matrix:
      os: [fedora-latest, ubuntu-latest, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        shell: bash
        run: pyinstaller --noconfirm --windowed main.py

      - name: Upload artifact (${{ matrix.os }})
        uses: actions/upload-artifact@v4
        with:
          name: PassManaging-${{ matrix.os }}-v_${{ substr(github.sha, 0, 7) }}
          path: dist/
