name: Check Linux executable build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (Ubuntu)
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python dependencies (Ubuntu)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build and test Ubuntu executable
        run: pyinstaller --noconfirm --windowed main.py

      - name: Upload artifact (Ubuntu)
        uses: actions/upload-artifact@v4
        with:
          name: PassManaging-ubuntu-PR_${{ github.event.pull_request.number }}
          path: dist/

      - name: Build and test Fedora executable in Docker
        shell: bash
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app fedora:latest bash -c "
            dnf install -y python3-pip python3-devel gcc make &&
            python3 -m pip install --upgrade pip &&
            pip3 install -r requirements.txt &&
            pip3 install pyinstaller &&
            pyinstaller --noconfirm --windowed main.py &&
            dnf remove -y gcc make python3-devel &&
            dnf clean all
          "

      - name: Upload artifact (Fedora)
        uses: actions/upload-artifact@v4
        with:
          name: PassManaging-fedora-PR_${{ github.event.pull_request.number }}
          path: dist/