name: Check Windows Executable Build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if main.spec has changed
        id: check-main-spec
        shell: bash
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "^main.spec$"; then
            echo "main.spec has changed."
            echo "continue=true" >> $GITHUB_ENV
          else
            echo "main.spec has not changed."
            echo "continue=false" >> $GITHUB_ENV
          fi

      - name: Set up Python
        if: env.continue == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        if: env.continue == 'true'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test build executable
        if: env.continue == 'true'
        run: pyinstaller --noconfirm main.spec

      - name: Upload executable artifact
        if: env.continue == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: built-executable-PR_${{ github.event.pull_request.number }}
          path: dist/