name: Build Windows Executable

on:
  push:
    branches:
      - '**'   # Build on all branches

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        runtime:
          - win-x64
          - win-arm64
        include:
        - runtime: win-x64
          os: windows-latest
        - runtime: win-arm64
          os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        shell: bash
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            pyinstaller --noconfirm --windowed --onefile  main.py
          else
            pyinstaller --clean --noconfirm --windowed --onefile --debug all main.py
          fi

      - name: Upload executable artifact (${{ matrix.runtime }})
        uses: actions/upload-artifact@v4
        with:
          # Use the branch name in the artifact name if not on main
          name: PassManaging-${{ matrix.runtime }}${{ github.ref_name != 'main' && format('-{0}', github.ref_name) || '' }}--v_${{ github.sha }}
          path: dist/