name: Check Windows executable build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Test build executable
        run: |
          pyinstaller --noconfirm --windowed main.py

      - name: Upload executable artifact (${{ matrix.os }})
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-PR_${{ github.event.pull_request.number }}
          path: dist/
